name: Security Scanning
on: [pull_request, push]

jobs:
  security:
    runs-on: ["innersource.prod.amr.dind"]
    steps:
      - uses: actions/checkout@v4
      - uses: intel-innersource/applications.security.monitoring.cas@v2
        with:
          sdl-api-key: ${{ secrets.1951f63a-bf40-40e4-a547-5094d415f847 }}
          sdl-project-id: ${{ secrets.e805d7f0-10e2-4b6e-9dc1-87ee95086fe0 }}